In [1]:
#Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:

import numpy as np
arr=np.arange(1,21)
arr

#In this we use the range function to get the numbers from 1 to 20

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
#Calculate the sum, mean, median, and standard deviation of the elements in the array.

print("Sum:",np.sum(arr))
print("Mean:",np.mean(arr))
print("Median:",np.median(arr))
print("Standard Deviation:",np.std(arr))

#In this we perform the mean, median,sum and the standard deviation by use the required functions



Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398


In [13]:
#Find the indices of elements greater than 10 in the array.

indicies=np.where(arr > 10)[0]
indicies
#we print the array of the elements  greater than 10


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int64)

In [ ]:
#2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  

In [15]:
array=np.arange(1,17).reshape(4,4)
array
# we print the array of elements

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
# b. Find the transpose of the array.  

Transpose=np.transpose(array)
Transpose

# transposing of the array is done in this by using the function transpose

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [9]:
#c. Calculate the row-wise sums of the array.

import numpy as np
array=np.arange(1,17).reshape(4,4)
row=np.sum(array,axis=1)
row



array([10, 26, 42, 58])

In [8]:
#c. Calculate the column-wise sums of the array.
col=np.sum(array,axis=0)
col

array([28, 32, 36, 40])

In [30]:

#3. Create two 3 X 3 arrays filled with random integers between 1 and 20.  
array2=np.random.randint(21,size=(3,3))
array1   #printing array 1

array([[17,  0, 13],
       [16,  1, 10],
       [11,  9,  8]])

In [31]:
array2 #printing array 2

array([[ 2, 12, 10],
       [17, 11, 14],
       [11, 19,  7]])

In [32]:
#a. Perform element-wise addition

add=array1+array2
add

array([[19, 12, 23],
       [33, 12, 24],
       [22, 28, 15]])

In [33]:
#a. Perform element-wise subtraction 
sub=array1-array2
sub

array([[ 15, -12,   3],
       [ -1, -10,  -4],
       [  0, -10,   1]])

In [34]:
#a. Perform element-wise  multiplication. 

mul=array1*array2
mul

array([[ 34,   0, 130],
       [272,  11, 140],
       [121, 171,  56]])

In [35]:
#b. Compute the dot product of the two arrays.  

dot=np.dot(array1,array2)
dot

array([[177, 451, 261],
       [159, 393, 244],
       [263, 383, 292]])

In [52]:
# Creating 1D array
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
#reshaping 1D array into 3X4 2D array
b=a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
# slicing the first 2 rows and last 2 columns
sliced = b[:2, -2:]
sliced

array([[2, 3],
       [6, 7]])